### ISSUE TITLE
[Bug]: Routine step with "uses" and "run"

### ISSUE THREAD

**Issue by oneofthezombies** [dogu-team/dogu#408]
### Environment

Cloud

### Steps to reproduce

1. Create Dogu Routine with
```
# ...
steps:
  - uses: dogu-actions/run-test
    run: echo hello
# ...
```

### Expected behavior

The "uses" and "run" cannot be used at the same time and must fail to save.

### Actual behavor

Both "uses" and "run" are saved, and the actual action is only "uses".

### Version

Dogu 1.10.0
