### ISSUE TITLE
[Refactor]: Routine runs-on.platformName to runs-on.tag

### ISSUE THREAD

**Issue by oneofthezombies** [dogu-team/dogu#409]
### Problem

platformName matches with dogu device tags.
Therefore, when adding a custom tag, there is confusion in name matching.

### Update

runs-on.platformName to runs-on.tag

**Comment by Ikalli** [comment]
For multiple device hit, what if add targeting method optional property like `select: pick-all` ..?

For example,
```yaml
runs-on:
  browserName: chrome
  tag: macos
  select: pick-all # default behavior: pick one device 
```

Also, supporting multiple `browserName` and `tag`  would be more convenient in UX.

For example,
```yaml
runs-on:
  browserNames:
    - chrome
    - firefox
  tags:
    - macos
    - my-windows
```

**Comment by Ikalli** [comment]
I think allowing multiple `browserName` and `tag` seems higher priority than running tests on multiple devices

**Comment by oneofthezombies** [comment]
```
runs-on:
  browserName: chrome
  tag: macos
  select: pick-all # default behavior: pick one device 
```
to 
```
runs-on:
  browserName: chrome
  group: macos
```

**Comment by Ikalli** [comment]
Full YAML schema for multiple `browserName` and `tag` will be:

```yaml
name: sample-routine

on:
  workflow_dispatch: null
  
jobs:
  sample-job:
    runs-on:
      browserName:
        - chrome
        - firefox
      tag:
        - macos
        - windows
    steps:
      - name: run test
        uses: dogu-actions/run-test
        with:
          checkout: true
          command: echo hello
    record: true
```
